from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: RejaReja
    Package: TestProject.Generated.Tests.RejaReja
    Test: Rejareja cart
    Generated by: Emmanuel Bore (emmanuhkipngetich@gmail.com)
    Generated on 03/14/2022, 09:59:10
"""


@pytest.fixture()
def driver():
    capabilities = {
        "platformName": "Android",
        "udid": "R58R61XCMMJ",
        "appPackage": "com.dukatech.digiduka",
        "appActivity": "com.dukatech.digiduka.ui.views.ui.dashboard.DashboardActivity",
    }
    driver = webdriver.Remote(token="FleuoSg2jb_Q_OkT_4gUmMw3_h5z2s7WejhfakYqpsQ",
                              project_name="RejaReja_Retail",
                              job_name="Rejareja cart",
                              desired_capabilities=capabilities)
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):

    # 1. Click 'com.dukatech.digiduka:id/navigation_b...1'
    com_dukatech_digiduka_colon_id_slash_navigation_b_1 = driver.find_element(By.XPATH,
                                                                              "//android.widget.FrameLayout[2]/android.widget.FrameLayout/android.widget.ImageView")
    com_dukatech_digiduka_colon_id_slash_navigation_b_1.click()

    # 2. Click 'Ndovu Home Baking 1x50kg'
    ndovu_home_baking_1x50kg = driver.find_element(By.XPATH,
                                                   "//android.widget.TextView[@text = 'Ndovu Home Baking 1x50kg']")
    ndovu_home_baking_1x50kg.click()

    # 3. Click 'com.dukatech.digiduka.orders:id/ivBsB...'
    com_dukatech_digiduka_orders_colon_id_slash_ivbsb_ = driver.find_element(By.ID,
                                                                             "com.dukatech.digiduka.orders:id/ivBsBuyProdPlus")
    com_dukatech_digiduka_orders_colon_id_slash_ivbsb_.click()

    # 4. Click 'Add To Cart'
    add_to_cart = driver.find_element(By.ID,
                                      "com.dukatech.digiduka.orders:id/btBSBuyFragContinueShopping")
    add_to_cart.click()

    # 5. Click 'Ndovu Home Baking 24x0.5kg'
    ndovu_home_baking_24x0_5kg = driver.find_element(By.XPATH,
                                                     "//android.widget.TextView[@text = 'Ndovu Home Baking 24x0.5kg']")
    ndovu_home_baking_24x0_5kg.click()

    # 6. Click 'com.dukatech.digiduka.orders:id/ivBsB...'
    com_dukatech_digiduka_orders_colon_id_slash_ivbsb_ = driver.find_element(By.ID,
                                                                             "com.dukatech.digiduka.orders:id/ivBsBuyProdPlus")
    com_dukatech_digiduka_orders_colon_id_slash_ivbsb_.click()

    # 7. Click 'Add To Cart'
    add_to_cart = driver.find_element(By.ID,
                                      "com.dukatech.digiduka.orders:id/btBSBuyFragContinueShopping")
    add_to_cart.click()

    # 8. Click 'Ndovu Home Baking 6x2kg'
    ndovu_home_baking_6x2kg = driver.find_element(By.XPATH,
                                                  "//android.widget.TextView[@text = 'Ndovu Home Baking 6x2kg']")
    ndovu_home_baking_6x2kg.click()

    # 9. Click 'com.dukatech.digiduka.orders:id/ivBsB...'
    com_dukatech_digiduka_orders_colon_id_slash_ivbsb_ = driver.find_element(By.ID,
                                                                             "com.dukatech.digiduka.orders:id/ivBsBuyProdPlus")
    com_dukatech_digiduka_orders_colon_id_slash_ivbsb_.click()

    # 10. Click 'Add To Cart'
    add_to_cart = driver.find_element(By.ID,
                                      "com.dukatech.digiduka.orders:id/btBSBuyFragContinueShopping")
    add_to_cart.click()

    # 11. Click '3'
    _3 = driver.find_element(By.ID,
                             "com.dukatech.digiduka:id/tvCartItemCountBadge")
    _3.click()

    # 12. Click 'Ndovu Home Baking 1x50kg1'
    ndovu_home_baking_1x50kg1 = driver.find_element(By.XPATH,
                                                    "//android.widget.TextView[@text = 'Ndovu Home Baking 1x50kg']")
    ndovu_home_baking_1x50kg1.click()

    # 13. Does 'Ndovu Home Baking 24x0.5kg1' contain 'Ndovu Home Baking 24x0.5kg'?
    ndovu_home_baking_24x0_5kg1 = driver.find_element(By.XPATH,
                                                      "//android.widget.TextView[@text = 'Ndovu Home Baking 24x0.5kg']")
    step_output = ndovu_home_baking_24x0_5kg1.text
    assert step_output and ("Ndovu Home Baking 24x0.5kg" in step_output)

    # 14. Does 'Ndovu Home Baking 6x2kg1' contain 'Ndovu Home Baking 6x2kg'?
    ndovu_home_baking_6x2kg1 = driver.find_element(By.XPATH,
                                                   "//android.widget.TextView[@text = 'Ndovu Home Baking 6x2kg']")
    step_output = ndovu_home_baking_6x2kg1.text
    assert step_output and ("Ndovu Home Baking 6x2kg" in step_output)
